cask_args appdir: '/Applications'
tap 'homebrew/bundle'

brew 'openssl'
brew 'wget'
brew 'zsh-autosuggestions'

cask '1password'
cask 'tunnelbear'
cask 'iterm2'
cask 'slack'
cask 'skype'
cask 'evernote'
cask 'sourcetree'
cask 'sublime-text'
cask 'charles'
cask 'paw'
cask 'fastlane'