cask_args appdir: '/Applications'
tap 'homebrew/bundle'
brew 'openssl'
brew 'wget'
brew 'gpg'
cask 'iterm2'
cask 'slack'
cask 'charles'
cask 'paw'
cask '1password'
cask '1password/tap/1password-cli'
cask 'google-chrome'
cask 'tunnelbear'
cask 'notion'
cask 'sourcetree'
